/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Arthur
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public FormPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnCadastroClientes = new javax.swing.JButton();
        btnProdutoConveniencia = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnGerenciarConveniencia = new javax.swing.JButton();
        btnListaClientes = new javax.swing.JButton();
        btnGerenciarPosto = new javax.swing.JButton();
        btnProdutoPosto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1191, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        btnCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/users1-1-64.png"))); // NOI18N
        btnCadastroClientes.setText("Cadastrar Clientes  ");
        btnCadastroClientes.setFocusable(false);
        btnCadastroClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClientesActionPerformed(evt);
            }
        });

        btnProdutoConveniencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file-roller.png"))); // NOI18N
        btnProdutoConveniencia.setText("   Produtos Conveniência");
        btnProdutoConveniencia.setFocusable(false);
        btnProdutoConveniencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProdutoConveniencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProdutoConveniencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoConvenienciaActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_exit_to_app_48px-64.png"))); // NOI18N
        btnLogout.setText("  Logout");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/info.png"))); // NOI18N
        btnInfo.setText("  Info");
        btnInfo.setFocusable(false);
        btnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnGerenciarConveniencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/marketing-20-64.png"))); // NOI18N
        btnGerenciarConveniencia.setText(" Gerenciar Conveniência");
        btnGerenciarConveniencia.setFocusable(false);
        btnGerenciarConveniencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGerenciarConveniencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGerenciarConveniencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarConvenienciaActionPerformed(evt);
            }
        });

        btnListaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/searchuser3-64.png"))); // NOI18N
        btnListaClientes.setText("   Gerenciar Clientes");
        btnListaClientes.setFocusable(false);
        btnListaClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListaClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaClientesActionPerformed(evt);
            }
        });

        btnGerenciarPosto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Gas-pump_1.png"))); // NOI18N
        btnGerenciarPosto.setText("  Gerenciar Posto");
        btnGerenciarPosto.setFocusable(false);
        btnGerenciarPosto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGerenciarPosto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGerenciarPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarPostoActionPerformed(evt);
            }
        });

        btnProdutoPosto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/GasStation.png"))); // NOI18N
        btnProdutoPosto.setText(" Produtos Posto");
        btnProdutoPosto.setFocusable(false);
        btnProdutoPosto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProdutoPosto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProdutoPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoPostoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastroClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListaClientes)
                .addGap(46, 46, 46)
                .addComponent(btnProdutoPosto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerenciarPosto)
                .addGap(40, 40, 40)
                .addComponent(btnProdutoConveniencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerenciarConveniencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(btnGerenciarConveniencia)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCadastroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProdutoPosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGerenciarPosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProdutoConveniencia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btnInfo))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoConvenienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoConvenienciaActionPerformed
        abrirFormulario(new FormCadProdConveniencia());
                                    
    }//GEN-LAST:event_btnProdutoConvenienciaActionPerformed

    private void btnCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClientesActionPerformed
        
         abrirFormulario(new FormCadClientes());   
    }//GEN-LAST:event_btnCadastroClientesActionPerformed

    private void btnListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaClientesActionPerformed
        
            abrirFormulario(new FormVisualizadorClientes());
    }//GEN-LAST:event_btnListaClientesActionPerformed

    private void btnProdutoPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoPostoActionPerformed
        
            abrirFormulario(new FormCadProdPosto());
    }//GEN-LAST:event_btnProdutoPostoActionPerformed

    private void btnGerenciarPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarPostoActionPerformed
        
            abrirFormulario(new FormVisualizadorPosto());
    }//GEN-LAST:event_btnGerenciarPostoActionPerformed

    private void btnGerenciarConvenienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarConvenienciaActionPerformed
        
            abrirFormulario(new FormVisualizadorConveniencia());
    }//GEN-LAST:event_btnGerenciarConvenienciaActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        
            abrirFormulario(new FormSobre());
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
            System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroClientes;
    private javax.swing.JButton btnGerenciarConveniencia;
    private javax.swing.JButton btnGerenciarPosto;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnListaClientes;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProdutoConveniencia;
    private javax.swing.JButton btnProdutoPosto;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

private void abrirFormulario(JInternalFrame f) {
        if (jDesktopPane1.getAllFrames().length == 0) {
            jDesktopPane1.add(f);

            Dimension d = f.getDesktopPane().getSize();
            f.setLocation(
                    (d.width - f.getSize().width) / 2,
                    (d.height - f.getSize().height) / 2
            );

            f.setVisible(true);
        }

    }
}
