/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import controller.dao.ProdutoPostoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class FormCadProdPosto extends javax.swing.JInternalFrame {

     
    /**
     * Creates new form FormCadProdPosto
     */
    public FormCadProdPosto() {
        initComponents();
        novoProduto();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnCadPosto = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblLitros = new javax.swing.JLabel();
        lblVlUnitario = new javax.swing.JLabel();
        lblVlTotal = new javax.swing.JLabel();
        spnLitros = new javax.swing.JSpinner();
        txtVlUnitario = new javax.swing.JTextField();
        txtVlTotal = new javax.swing.JTextField();
        lblCombustivel = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCombustivel = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Bomba Combustivel");

        lblId.setText("Id");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtId, org.jdesktop.beansbinding.ELProperty.create("${editable}false"), txtId, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtId, org.jdesktop.beansbinding.ELProperty.create("${enabled}false"), txtId, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        lblLitros.setText("Litros");

        lblVlUnitario.setText("VL Litro");

        lblVlTotal.setText("VL Total");

        spnLitros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnLitrosspnQuantidadeStateChanged(evt);
            }
        });

        txtVlUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVlUnitariotxtVlUnitarioKeyReleased(evt);
            }
        });

        txtVlTotal.setText("R$ ");

        lblCombustivel.setText("Combustivel");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovobtnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarbtnSalvarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gas_station-64.png"))); // NOI18N

        javax.swing.GroupLayout pnCadPostoLayout = new javax.swing.GroupLayout(pnCadPosto);
        pnCadPosto.setLayout(pnCadPostoLayout);
        pnCadPostoLayout.setHorizontalGroup(
            pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadPostoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblId)
                    .addComponent(txtId)
                    .addComponent(lblVlUnitario)
                    .addComponent(txtVlUnitario)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadPostoLayout.createSequentialGroup()
                        .addComponent(lblCombustivel)
                        .addGap(101, 101, 101)
                        .addComponent(lblLitros))
                    .addGroup(pnCadPostoLayout.createSequentialGroup()
                        .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtVlTotal)
                            .addComponent(lblVlTotal)
                            .addComponent(txtCombustivel))
                        .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCadPostoLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(spnLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadPostoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addContainerGap())))))
        );
        pnCadPostoLayout.setVerticalGroup(
            pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadPostoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblCombustivel)
                    .addComponent(lblLitros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVlUnitario)
                    .addComponent(lblVlTotal))
                .addGap(1, 1, 1)
                .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadPostoLayout.createSequentialGroup()
                        .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnCadPostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCadPosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCadPosto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnLitrosspnQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnLitrosspnQuantidadeStateChanged
        calcularValorTotal();
    }//GEN-LAST:event_spnLitrosspnQuantidadeStateChanged

    private void txtVlUnitariotxtVlUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVlUnitariotxtVlUnitarioKeyReleased
        calcularValorTotal();
    }//GEN-LAST:event_txtVlUnitariotxtVlUnitarioKeyReleased

    private void btnNovobtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovobtnNovoActionPerformed
        novoProduto();
    }//GEN-LAST:event_btnNovobtnNovoActionPerformed

    private void btnSalvarbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarbtnSalvarActionPerformed
          ProdutoPosto c = new ProdutoPosto();
        if (!txtId.getText().isEmpty()) {
            c.setId(Integer.parseInt(txtId.getText()));
        }
        c.setId_combustivel(Integer.parseInt(
                txtCombustivel.getText().toString()));
        c.setLitros(Integer.parseInt(
                spnLitros.getValue().toString()));      
       c.setVllitro(Double.parseDouble(
                txtVlUnitario.getText().toString()));
       c.setVltotal(Double.parseDouble(
                txtVlTotal.getText().toString())); 

        
        int res = -1;

        if (c.getId() == 0) {
            res = new ProdutoPostoDAO().inserir(c);
            txtId.setText(String.valueOf(res));
        } else {
            res = new ProdutoPostoDAO().atualizar(c);
        }

        if (res != -1) {
            JOptionPane.showMessageDialog(null,
                "Operação realizada com sucesso!",
                "Posto", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                "Ocorreu um erro ao realizar a operação.",
                "Posto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarbtnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCombustivel;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLitros;
    private javax.swing.JLabel lblVlTotal;
    private javax.swing.JLabel lblVlUnitario;
    private javax.swing.JPanel pnCadPosto;
    private javax.swing.JSpinner spnLitros;
    private javax.swing.JTextField txtCombustivel;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtVlTotal;
    private javax.swing.JTextField txtVlUnitario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        txtId.setText("");
        txtCombustivel.setText("");
        spnLitros.setValue(0);
        txtVlUnitario.setText("");
        txtVlTotal.setText("");
        
    }

    private void novoProduto() {
        limparCampos();
        txtCombustivel.setEnabled(true);
        spnLitros.setEnabled(true);
        txtVlUnitario.setEnabled(true);
        txtVlTotal.setEnabled(true); 
    }
    
    
    
    private void calcularValorTotal() {
        try {
            int qtde = Integer.parseInt(spnLitros.getValue().toString());
            double vlunit = Double.parseDouble(txtVlUnitario.getText());
            String res = String.valueOf(qtde * vlunit);
            txtVlTotal.setText(res);
        } catch (Exception e) {
            txtVlTotal.setText("");
        }
}
    
}
