/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import controller.Conexao;
import controller.dao.CombustivelDAO;
import controller.dao.ProdutoPostoDAO;
import java.sql.Connection;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import report.Relatorio;

/**
 *
 * @author Arthur
 */
public class FormVisualizadorPosto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormVisualizadorClientes
     */
    public FormVisualizadorPosto() {
        initComponents();
        configurarFormulario();
        List<Object> lista = null;
        lista = new ProdutoPostoDAO().listar();
        exibirTarefas(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTabela = new javax.swing.JScrollPane();
        tabTarefas = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnRel = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Combustivel");

        tabTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Combustivel", "Litros", "Valor Unitario"
            }
        ));
        tabTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTarefasMouseClicked(evt);
            }
        });
        spTabela.setViewportView(tabTarefas);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnRel.setText("Relatorio");
        btnRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addComponent(txtPesquisar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnRel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTarefasMouseClicked
        
    }//GEN-LAST:event_tabTarefasMouseClicked

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        if(txtPesquisar.getText().equals("")){
            List<Object> lista = null;
        lista = new ProdutoPostoDAO().listar();
        exibirTarefas(lista);           
        }else{
         List<Object> lista = null;
        lista = new ProdutoPostoDAO().pesquisarPorId(Integer.parseInt(txtPesquisar.getText()));
        exibirTarefas(lista);}  
        
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelActionPerformed
    Connection con= Conexao.Conectar();
        String rpt = "bomba.jrxml";
        new Relatorio().exibir(con, rpt);
    }//GEN-LAST:event_btnRelActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRel;
    private javax.swing.JScrollPane spTabela;
    private javax.swing.JTable tabTarefas;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

 private void configurarFormulario() {

        //DISPOSE_ON_CLOSE = FECHAR APENAS O FORM ATUAL
        this.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);

        configurarTabela();
          
        
    }

    

    private void exibirTarefas(List<Object> lista){    

        
        if(lista != null){
            if(lista.size() > 0){
            configurarTabela();
            DefaultTableModel m = (DefaultTableModel)tabTarefas.getModel();
            
                for (Object obj : lista) {
                    ProdutoPosto pl = (ProdutoPosto)obj;
                    List<Object> lista1 = null;
                    lista1 = new CombustivelDAO().pesquisarPorId(pl.getId_combustivel());
                    
                    for (Object obj1 : lista1) {
                    Combustivel tp = (Combustivel)obj1;
                    m.addRow(new Object[]{
                        pl.getId(),
                        pl.getLitros(),
                        pl.getVllitro(),
                        pl.getVltotal(),
                        tp.getNome()
                    });
                    }
                    
                    
                    
                
                }
                tabTarefas.setModel(m);
           
            }
        }
    }
    
    private void configurarTabela() {
        DefaultTableModel m = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        m.addColumn("Id");
        m.addColumn("Litros");
        m.addColumn("Valor/L");
        m.addColumn("Valor Total");        
        m.addColumn("Combustivel");        
        tabTarefas.setModel(m);
        tabTarefas.getTableHeader().setReorderingAllowed(false);
    }
    
    public class UpperCaseDocument extends PlainDocument {

        @Override
        public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
            super.insertString(offs, str.toUpperCase(), a);
        }
    }
}

