/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;


import controller.Conexao;
import controller.dao.ProdutoConvenienciaDAO;
import java.sql.Connection;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import report.Relatorio;

/**
 *
 * @author Arthur
 */
public class FormVisualizadorConveniencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormVisualizadorClientes
     */
    public FormVisualizadorConveniencia() {
      initComponents();
        configurarFormulario();
        List<Object> lista = null;
        lista = new ProdutoConvenienciaDAO().listar();
        exibirTarefas(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTabela = new javax.swing.JScrollPane();
        tabTarefas = new javax.swing.JTable();
        pnConsultar = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JFormattedTextField();
        btnRel = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Produtos");

        tabTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Categoria", "Quantidade", "Valor Unitario"
            }
        ));
        tabTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTarefasMouseClicked(evt);
            }
        });
        spTabela.setViewportView(tabTarefas);

        pnConsultar.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnConsultarLayout = new javax.swing.GroupLayout(pnConsultar);
        pnConsultar.setLayout(pnConsultarLayout);
        pnConsultarLayout.setHorizontalGroup(
            pnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisar)
                .addContainerGap())
        );
        pnConsultarLayout.setVerticalGroup(
            pnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConsultarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnRel.setText("Relatorio");
        btnRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addComponent(pnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTarefasMouseClicked
        
    }//GEN-LAST:event_tabTarefasMouseClicked

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        List<Object> lista2 = null;
        lista2 = new ProdutoConvenienciaDAO().pesquisarPorNome(txtPesquisar.getText());
        exibirTarefas(lista2);
        
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelActionPerformed
      Connection con= Conexao.Conectar();
        String rpt = "conveniencia.jrxml";
        new Relatorio().exibir(con, rpt);
    }//GEN-LAST:event_btnRelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRel;
    private javax.swing.JPanel pnConsultar;
    private javax.swing.JScrollPane spTabela;
    private javax.swing.JTable tabTarefas;
    private javax.swing.JFormattedTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

 private void configurarFormulario() {

        //DISPOSE_ON_CLOSE = FECHAR APENAS O FORM ATUAL
        this.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);

        configurarTabela();
 }
  
  
 
 
 private void exibirTarefas(List<Object> lista){    
 
       if (lista.size() > 0) {
            configurarTabela();
            DefaultTableModel m = (DefaultTableModel) tabTarefas.getModel();
            for (Object p : lista) {
                ProdutoConveniencia pl = (ProdutoConveniencia)p;
                m.addRow(new Object[]{
                        pl.getId(),
                        pl.getNome(),
                        pl.getVlunitario(),
                        pl.getQuantidade()
                    
                });
            }
            tabTarefas.setModel(m);

        }
    }
            
        
    
    

    private void configurarTabela() {
        DefaultTableModel m = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        m.addColumn("ID");       
        m.addColumn("Nome");     
        m.addColumn("Valor Unitario");
        m.addColumn("Quantidade");
        tabTarefas.setModel(m);
        tabTarefas.getTableHeader().setReorderingAllowed(false);
    }

    
}

